### ISSUE TITLE
[fwc] todo checklist

### ISSUE THREAD

**Issue by 7yl4r** [marinebon/mbon-dashboard-server#6]
* [x] overview map needs new bouys
* [x] west florida river panel missing
* [x] links to ftp directories are missing
* [x] create human-readable csv files
* [x] link human-readable csv files
* [x] make dashboards "public" [[ref](https://stackoverflow.com/questions/33111835/how-to-set-up-grafana-so-that-no-password-is-necessary-to-view-dashboards)]
* [x] add coastal ROI and sentinel sites (SS) to FGBNMS board (COAST1, COAST2, COAST3, COAST4 and SS(1-8)
* [x] coral disease observations are missing

**Comment by dotis** [comment]
Human readable .csv files will be complete after tonight's cron jobs. They are in the same place(s) as the current .csv files, but have a suffix "user_output.csv" at the end of each filename. These are for sat files, USGS discharge and buoy temp/sal for the FKNMS and FWC boards.

**Comment by dotis** [comment]
I have created new maps that show buoy locations (FWC and FKNMS) and for FGBNMS that shows the coastal ROI. They are here:
https://github.com/marinebon/mbon-dashboard-server/tree/master/static_files

**Comment by 7yl4r** [comment]
RE making dashboards public: 

The configuration in the docker-compose.yml file was set correctly and public viewing was working for fk and fgb but not for fwc.
The cause of this was that I had set the "Organization Name" from the web GUI.
Changing the Org Name back to the default ("Main Org.") fixed the issue.
